# Generated by Django 5.2 on 2025-04-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_subscribers_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='author',
        ),
    ]
